apiVersion: v1
kind: Secret
metadata:
  name: vault-sa-token  # The name of the token secret
  annotations:
    kubernetes.io/service-account.name: "vault"  # The service account name
type: kubernetes.io/service-account-token